/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './app/routes/_authenticated/route'
import { Route as authLoginRouteImport } from './app/routes/(auth)/login'
import { Route as AuthenticatedIndexRouteImport } from './app/routes/_authenticated/index'
import { Route as AuthenticatedCategoriesIndexRouteImport } from './app/routes/_authenticated/categories/index'
import { Route as AuthenticatedKitchenIndexRouteImport } from './app/routes/_authenticated/kitchen/index'
import { Route as AuthenticatedMenuIndexRouteImport } from './app/routes/_authenticated/menu/index'
import { Route as AuthenticatedOrdersIndexRouteImport } from './app/routes/_authenticated/orders/index'
import { Route as AuthenticatedProductsIndexRouteImport } from './app/routes/_authenticated/products/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './app/routes/_authenticated/reports/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './app/routes/_authenticated/settings/index'
import { Route as AuthenticatedShiftsIndexRouteImport } from './app/routes/_authenticated/shifts/index'
import { Route as AuthenticatedStaffIndexRouteImport } from './app/routes/_authenticated/staff/index'
import { Route as AuthenticatedTablesIndexRouteImport } from './app/routes/_authenticated/tables/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriesIndexRoute =
  AuthenticatedCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKitchenIndexRoute =
  AuthenticatedKitchenIndexRouteImport.update({
    id: '/kitchen/',
    path: '/kitchen/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMenuIndexRoute = AuthenticatedMenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedShiftsIndexRoute =
  AuthenticatedShiftsIndexRouteImport.update({
    id: '/shifts/',
    path: '/shifts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTablesIndexRoute =
  AuthenticatedTablesIndexRouteImport.update({
    id: '/tables/',
    path: '/tables/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof authLoginRoute
  '/categories/': typeof AuthenticatedCategoriesIndexRoute
  '/kitchen/': typeof AuthenticatedKitchenIndexRoute
  '/menu/': typeof AuthenticatedMenuIndexRoute
  '/orders/': typeof AuthenticatedOrdersIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/shifts/': typeof AuthenticatedShiftsIndexRoute
  '/staff/': typeof AuthenticatedStaffIndexRoute
  '/tables/': typeof AuthenticatedTablesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/categories': typeof AuthenticatedCategoriesIndexRoute
  '/kitchen': typeof AuthenticatedKitchenIndexRoute
  '/menu': typeof AuthenticatedMenuIndexRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/shifts': typeof AuthenticatedShiftsIndexRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
  '/tables': typeof AuthenticatedTablesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/categories/': typeof AuthenticatedCategoriesIndexRoute
  '/_authenticated/kitchen/': typeof AuthenticatedKitchenIndexRoute
  '/_authenticated/menu/': typeof AuthenticatedMenuIndexRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/shifts/': typeof AuthenticatedShiftsIndexRoute
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute
  '/_authenticated/tables/': typeof AuthenticatedTablesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/categories/'
    | '/kitchen/'
    | '/menu/'
    | '/orders/'
    | '/products/'
    | '/reports/'
    | '/settings/'
    | '/shifts/'
    | '/staff/'
    | '/tables/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/categories'
    | '/kitchen'
    | '/menu'
    | '/orders'
    | '/products'
    | '/reports'
    | '/settings'
    | '/shifts'
    | '/staff'
    | '/tables'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/login'
    | '/_authenticated/'
    | '/_authenticated/categories/'
    | '/_authenticated/kitchen/'
    | '/_authenticated/menu/'
    | '/_authenticated/orders/'
    | '/_authenticated/products/'
    | '/_authenticated/reports/'
    | '/_authenticated/settings/'
    | '/_authenticated/shifts/'
    | '/_authenticated/staff/'
    | '/_authenticated/tables/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categories/': {
      id: '/_authenticated/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof AuthenticatedCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kitchen/': {
      id: '/_authenticated/kitchen/'
      path: '/kitchen'
      fullPath: '/kitchen/'
      preLoaderRoute: typeof AuthenticatedKitchenIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menu/': {
      id: '/_authenticated/menu/'
      path: '/menu'
      fullPath: '/menu/'
      preLoaderRoute: typeof AuthenticatedMenuIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shifts/': {
      id: '/_authenticated/shifts/'
      path: '/shifts'
      fullPath: '/shifts/'
      preLoaderRoute: typeof AuthenticatedShiftsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tables/': {
      id: '/_authenticated/tables/'
      path: '/tables'
      fullPath: '/tables/'
      preLoaderRoute: typeof AuthenticatedTablesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCategoriesIndexRoute: typeof AuthenticatedCategoriesIndexRoute
  AuthenticatedKitchenIndexRoute: typeof AuthenticatedKitchenIndexRoute
  AuthenticatedMenuIndexRoute: typeof AuthenticatedMenuIndexRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedShiftsIndexRoute: typeof AuthenticatedShiftsIndexRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
  AuthenticatedTablesIndexRoute: typeof AuthenticatedTablesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCategoriesIndexRoute: AuthenticatedCategoriesIndexRoute,
  AuthenticatedKitchenIndexRoute: AuthenticatedKitchenIndexRoute,
  AuthenticatedMenuIndexRoute: AuthenticatedMenuIndexRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedShiftsIndexRoute: AuthenticatedShiftsIndexRoute,
  AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
  AuthenticatedTablesIndexRoute: AuthenticatedTablesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
